blog/urls.py
from django.conf.urls import patterns, include, url
from . import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^microblog/', include('microblog.foo.urls')),

    url(r'^$', views.BlogListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)', views.BlogDetailView.as_view(), name="detail"),
    #url(r"^$", blog_list),
)

menglewis/urls.py
from django.conf.urls import patterns, include, url
from .views import HomePageView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^microblog/', include('microblog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', HomePageView.as_view(), name='home'),
    #url(r"^$", blog_list),
)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True

class Post(TimeStampedModel):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    author = models.ForeignKey(User, related_name='posts')
    published = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    def __save__(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("blog:detail", (), {"slug": self.slug})

    class Meta:
        ordering = ["-created_at", "title"]

class Comment(TimeStampedModel):
    content = models.TextField()
    author = models.ForeignKey(User, related_name='comments')
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return self.content[0:20]

    class Meta:
        ordering = ["created_at"]

blog/views.py
# Create your views here.
from .models import Post
from django.views.generic import ListView, DetailView


class PublishedPostsMixin(object):
    def get_queryset(self):
        queryset = super(PublishedPostsMixin, self).get_queryset()
        return queryset.filter(published=True)

class BlogListView(PublishedPostsMixin, ListView):
    model = Post
    template_name = "post_list.html"


class BlogDetailView(PublishedPostsMixin, DetailView):
    model = Post
    template_name = "post_detail.html"

menglewis/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "index.html"

blog/templates/blog/post_detail.html
{% extends "_layouts/base.html" %}

{% block page_title %}{{ post.title }} | {% endblock %}

{% block page_content %}
<h2>{{ post.title }}</h2>
{{ post.content|linebreaks}}
<p>{{ post.updated }}</p>
{% for comment in post.comment_set.all %}
{{ comment.author }}<br/>
{{ comment.content }}<br/><br/>
{% endfor %}
<p><a href="{% url 'blog:list' %}">Blog List</a></p>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h1>Blog Posts</h1>
<ul>
    {% for post in post_list %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

templates/_layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block page_title %}{% endblock %}Microblog</title>
        <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
    </head>
    <body>
        {% block page_content %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog Home{% endblock %}

{% block page_content %}
<h1>Blog Home</h1>
<ul>
    <li><a href="{% url 'blog:list' %}">Go to Blog posts</a></li>
</ul>
{% endblock %}